
#ifndef KEYPAD_PRIVATE_H_
#define KEYPAD_PRIVATE_H_

#include "CPU_Configuration.h"

#define KEYPAD_PORT_OUT DIO_PORTC
#define KEYPAD_PORT_INP DIO_PORTD

#define KEYPAD_PIN_OUT0 DIO_PIN5
#define KEYPAD_PIN_OUT1 DIO_PIN4
#define KEYPAD_PIN_OUT2 DIO_PIN3
#define KEYPAD_PIN_OUT3 DIO_PIN2

#define KEYPAD_PIN_INP0 DIO_PIN7
#define KEYPAD_PIN_INP1 DIO_PIN6
#define KEYPAD_PIN_INP2 DIO_PIN5
#define KEYPAD_PIN_INP3 DIO_PIN3

#define KEYPAD_INP  DIO_INPUT
#define KEYPAD_OUT  DIO_OUTPUT

#define KEYPAD_LOW  DIO_LOW
#define KEYPAD_HIGH DIO_HIGH

#define KEYPAD_COL_STRT 7
#define KEYPAD_COL_END  4

#define KEYPAD_ROW_STRT 2
#define KEYPAD_ROW_END  5

#define KEYPAD_PRESSED  0


ERROR_STATE KEYPAD_Initialize(void);

ERROR_STATE KEYPAD_Read(UINT8_t* keypad_char);





#endif /* KEYPAD_PRIVATE_H_ */
